// @ts-nocheck
import { ConnectButton, getDefaultWallets, RainbowKitProvider } from '@rainbow-me/rainbowkit';
import Link from 'next/link'; 
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useState, createContext, useContext } from 'react';
import { useForm, useFieldArray, Controller } from "react-hook-form";
import {
  usePrepareContractWrite,
  useContractWrite,
  useWaitForTransaction,
 WagmiConfig, createConfig, configureChains,  useAccount,
  useConnect,
  useDisconnect,
  useEnsAvatar,
  useEnsName,
} from 'wagmi'
import { alchemyProvider } from 'wagmi/providers/alchemy'
import { publicProvider } from 'wagmi/providers/public'
import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import "@rainbow-me/rainbowkit/styles.css";
import { polygon, polygonMumbai } from 'wagmi/chains'
import  EthereumAddressColorVisualizer from '../components/visualize';

const projectId='e7ede65a0ef6002faae103b19b53b1f3';
const { chains, publicClient} = configureChains(
  [  polygon, polygonMumbai ],
 [
    alchemyProvider({ apiKey: '2VkIpW1Vrkj1qp8F6TLZmT0DHkOCIJOj' }),
    publicProvider()
  ]
);
const { connectors } = getDefaultWallets({
  appName: 'My RainbowKit App',
  projectId: 'e7ede65a0ef6002faae103b19b53b1f3',
  chains
});

const wagmiConfig = createConfig({
  autoConnect: true,
  connectors,
  publicClient
})

const Home: NextPage = () => {

  return (
      <div>
    <div className={styles.container}>
      <Head>
        <title>ColorIdentity</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>



    <WagmiConfig config={wagmiConfig}>
  <RainbowKitProvider chains={chains}>
      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
            What's your color identity?
        </h1>
        <div>
            <EthereumAddressColorVisualizer  />
        </div>
      </main>
  </RainbowKitProvider>
    </WagmiConfig>

  <footer className={styles.footer}>
        Made with ❤️  by 0xakira.eth at 🌈
  </footer>
</div>
</div>
  );
};

export default Home;
